# permissions for end users to view testscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testscaler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keda-test-scaler
    app.kubernetes.io/part-of: keda-test-scaler
    app.kubernetes.io/managed-by: kustomize
  name: testscaler-viewer-role
rules:
- apiGroups:
  - scaler.test.keda.sh
  resources:
  - testscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaler.test.keda.sh
  resources:
  - testscalers/status
  verbs:
  - get
